// final com "#": não adiciona "dias" no final
// final com "@": texto nenhum
const listEnding = [
  "longos",
  "míseros",
  "compridos",
  "lentos",
  "tortuosos",
  "sinuosos",
  "sofridos",
  "demorados",
  "intermináveis",
  "paulatinos",
  "traiçoeiros",
  "perversos",
  "ridículos",
  "radicais",
  "eucariontes",
  "vagarosos",
  "abençoados",
  "amaldiçoados",
  "inoxidáveis",
  "rugosos",
  "famigerados",
  "lacradores",
  "fofos",
  "síncronos e assíncronos",
  "catastróficos",
  "cínicos",
  "indiferenciáveis",
  "hilários",
  "eletrizantes",
  "hidratados",
  "perigosos",
  "duvidosos",
  "velozes e furiosos",
  "arretados",
  "preguiçosos",
  "eletrizantes",
  "inacabáveis",
  "di... como assim falta esse tanto?#",
  "pores-do-sol. ou é por-do-sols? não sei#",
  "misteriosos",
  "dolosos e culposos",
  "oxigenados",
  "pluricelulares",
  "variáveis",
  "calóricos",
  "voltas desse circular inverso que chamamos de terra#",
  "revolucionários",
  "ecléticos",
  "sensatos",
  "surpreendentes",
  "inesperados",
  "tecnológicos",
  "modernos",
  "abstratos",
  "feios",
  "gostosos",
  "acadêmicos",
  "românticos",
  "defenestrados",
  "esculachados",
  "estapafúrdios",
  "épicos",
  "geométricos",
  "inexoráveis",
  "sei lá que dia é hoje@",
  "hoje tô off@",
  "faltam ■■ dias@",
  "descubra@",
  "faltam alguns dias@",
  "você não vai acreditar em quantos dias faltam@",
  "insuportáveis",
];

const listEmojis = [
  "🔥",
  "😎",
  "😁",
  "😜",
  "🤪",
  "🥳",
  "💆‍♀️",
  "💃",
  "🛀",
  "🙌",
  "🎆",
  "🎇",
  "🍾",
  "🍷",
  "🧉",
  "🍸",
  "🍹",
  "🍺",
  "🍻",
  "🥂",
  "🥃",
  "🥤",
  "✈",
  "🏖",
  "💅",
];

const listError = ["🤔", "🤨", "🤯", "🤪", "🤩"];

const listPeople = [
  "valesca popozuda",
  "barraca do beijo",
  "é o tchan",
  "você",
  "eu",
  "jorge ben jor",
  "jorge e matheus",
  "jorge e mateus",
  "taylor swift",
  "buzz lightyear",
  "baco exu do blues",
  "beyoncé",
  "bruno e marrone",
  "bruno mars",
  "xuxa",
  "turma do balão mágico",
  "tupac",
  "snoop dogg",
  "sun tzu",
  "sócrates",
  "supermães",
  "david bowie",
  "djavan",
  "demi lovato",
  "pandora",
  "daniela mercury",
  "paul mccartney",
  "paulo coelho",
  "paulo freire",
  "paprika",
  "pabllo vittar",
  "para todos os garotos",
  "paralamas do sucesso",
  "Peaky Blinders",
  "PS. Eu Te Amo",
  "peter pan",
  "peter griffin",
  "manu gavassi",
  "miley cyrus",
  "michael jackson",
  "michael jordan",
  "michael scott",
  "michael douglas",
  "Filipe Ret",
  "fábio jr",
  "fábio porchat",
  "jô soares",
  "juliette freire",
];

export function newEnding() {
  return listEnding[Math.floor(Math.random() * listEnding.length)];
}

export function newEmoji(quantity = 1) {
  let returnString = "";
  for (let i = 0; i < quantity; i++) {
    returnString += listEmojis[Math.floor(Math.random() * listEmojis.length)];
  }
  return returnString;
}

export function newErrorEmoji() {
  return listError[Math.floor(Math.random() * listError.length)];
}

export function newPerson() {
  return listPeople[Math.floor(Math.random() * listPeople.length)];
}